core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    # Django admin
    path("dj-admin/", admin.site.urls),
    # User management
    path("accounts/", include("allauth.urls")),
    # Local
    path("", include("pages.urls")),
    path("profile/", include("users.urls")),
    path("images/", include("images.urls", namespace="images")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

images/urls.py
from django.urls import path

from images.views import ImageCreateView, ImageDetailView

app_name = "images"

urlpatterns = [
    path("create/", ImageCreateView.as_view(), name="create"),
    path("<slug:slug>/", ImageDetailView.as_view(), name="image_detail"),
]

pages/urls.py
from django.urls import path

from pages.views import (AboutPageView, ContactPageView, FeedbackPageView,
                         HomePageView)

app_name = 'pages'
urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('contact/', ContactPageView.as_view(), name='contact'),
    path('feedback/', FeedbackPageView.as_view(), name='feedback'),
    path('about/', AboutPageView.as_view(), name='about'),
]

templates/_alert.html
<!-- Start Alert -->
{% if messages %}
{% for message in messages %}
<div class="alert alert-{% if message.tags %}{{ message.tags }}{% endif %} alert-dismissible fade show">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    <div class="alert-icon">
        <i class="icon-check"></i>
    </div>
    <div class="alert-message">
        <span>{{ message }}</span>
    </div>
</div>
{% endfor %}
{% endif %}
<!-- End Alert -->

templates/_base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <!-- Font Awesome Icons -->
    <script src="https://kit.fontawesome.com/546230838a.js" crossorigin="anonymous"></script>

    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}" />
    <title>{% block title %}Bookmarks{% endblock title %}</title>
</head>

<body>
    <header>
        <!-- Fixed navbar -->
        <div class="d-flex flex-column flex-md-row justify-content-between align-items-center p-3 px-md-4\
         mb-3 bg-white">
            {% block appname %}
            <a href="{% url 'pages:home' %}" class="navbar-brand my-0 font-weight-normal">
                Bookmarks
            </a>
            {% endblock appname %}

            {% block navcenter %}{% endblock navcenter %}

            <nav class="my-2 my-md-0 mr-md-3">
                <a class="p-2 text-dark text-decoration-none" href="{% url 'images:create' %}">
                    <i class="fa fa-plus fa-lg" aria-hidden="true"></i>
                </a>
                <a class="p-2 text-dark text-decoration-none" href="">
                    <i class="fa fa-clipboard fa-lg" aria-hidden="true"></i>
                </a>
                <a class="p-2 text-dark text-decoration-none" href="">
                    <i class="fa fa-feather-alt fa-lg" aria-hidden="true"></i>
                </a>
                <a class="p-2 text-dark text-decoration-none" href="">
                    <i class="fa fa-user-secret fa-lg" aria-hidden="true"></i>
                </a>
                {% if user.is_authenticated %}
                <div class="btn-group">
                    <button type="button" class="btn dropdown-toggle" data-toggle="dropdown" aria-haspopup="true"
                        aria-expanded="false">
                        <i class="fa fa-user-circle-o fa-lg" aria-hidden="true"></i>
                    </button>
                    <div class="dropdown-menu dropdown-menu-right" style="width: 300px;">
                        <div class="my-5">
                            <p class="text-center">{{ user.get_full_name }}</p>
                            <p class="text-center font-weight-light">{{ user.email }}</p>
                            <a href="{{ user.profile.get_absolute_url }}">
                                <p class="text-center font-weight-light">Profile</p>
                            </a>
                        </div>
                        <div class="dropdown-divider"></div>
                        <a href="{% url 'account_logout' %}" class="dropdown-item p-md-3 text-center">
                            <i class="fa fa-sign-out fa-lg" aria-hidden="true"></i>
                            Signout
                        </a>
                        <div class="dropdown-divider"></div>
                        <div class="d-flex justify-content-around p-md-3">
                            <a href="{% url 'pages:feedback' %}">
                                <button type="submit" class="btn btn-light btn-sm">
                                    <small>Feedback</small>
                                </button>
                            </a>
                            <a href="">
                                <button type="submit" class="btn btn-light btn-sm">
                                    <small>Privacy</small>
                                </button>
                            </a>
                            <a href="">
                                <button type="submit" class="btn btn-light btn-sm">
                                    <small>Terms of service</small>
                                </button>
                            </a>
                        </div>
                    </div>

                </div>
                {% else %}
                <a class="p-2 text-dark text-decoration-none" href="{% url 'account_login' %}">
                    <i class="fa fa-sign-in fa-lg" aria-hidden="true"></i>
                </a>
                <a class="btn btn-light" href="{% url 'account_signup' %}">
                    <i class="fa fa-user-plus" aria-hidden="true"></i>
                </a>
                {% endif %}

            </nav>
        </div>
    </header>
    <div class="container-fluid">
        {% include '_alert.html' %}
        {% block content %}
        {% endblock content %}
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous">
    </script>
    <script>
        $('.toast').toast('show')
    </script>
    {% block js %}{% endblock js %}

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
</body>

</html>

templates/_toast.html
<div aria-live="polite" aria-atomic="true" style="position: relative; min-height: 1px;">
    <!-- Position it -->
    <div style="position: absolute; top: 0; right: 20px; min-width: 250px;">
        <!-- Then put toasts within -->
        {% if messages %}
        {% for message in messages %}
        <div class="toast" role="alert" aria-live="assertive" aria-atomic="true" data-delay=5000>
            <div class="toast-header">
                <i class="fas fa-boxes"></i>
                <strong class="mr-auto ml-3">Message</strong>
                <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="toast-body">
                {{ message }}
            </div>
        </div>
        {% endfor %}
        {% endif %}
    </div>
</div>

templates/base.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>{% block title %}Bookmarks{% endblock title %}</title>
</head>

<body>
    <div class="container">
        {% block content %}
        {% endblock content %}
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
        crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
</body>

</html>